-- AI Debate Archive content database schema.
-- This file adds the database-driven content layer without removing the
-- current slug-based engagement tables.

create extension if not exists pgcrypto;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.is_admin = true
  );
$$;

grant execute on function public.is_admin() to anon, authenticated;

create table if not exists public.debates (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title text not null,
  summary text not null default '',
  category text not null default '',
  status text not null default 'draft'
    check (status in ('draft', 'scheduled', 'published', 'archived')),
  publish_at timestamptz,
  cover_image_url text,
  cover_class text,
  affirmative_model text not null default '',
  negative_model text not null default '',
  judge_model text not null default '',
  winner text not null default ''
    check (winner in ('', 'affirmative', 'negative', 'tie')),
  winner_label text,
  affirmative_score numeric,
  negative_score numeric,
  score_total numeric,
  judge_summary text,
  source_dir text,
  source_markdown_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.debate_segments (
  id uuid primary key default gen_random_uuid(),
  debate_id uuid not null references public.debates(id) on delete cascade,
  round_key text not null,
  speaker_role text not null check (speaker_role in ('affirmative', 'negative', 'judge')),
  speaker_name text not null default '',
  title text not null,
  content text not null,
  sort_order integer not null,
  audio_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (debate_id, round_key),
  unique (debate_id, sort_order)
);

create table if not exists public.debate_scorecards (
  id uuid primary key default gen_random_uuid(),
  debate_id uuid not null references public.debates(id) on delete cascade,
  criterion text not null,
  affirmative_score numeric,
  negative_score numeric,
  comment text,
  sort_order integer not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (debate_id, sort_order)
);

create table if not exists public.debate_media (
  id uuid primary key default gen_random_uuid(),
  debate_id uuid not null references public.debates(id) on delete cascade,
  media_type text not null check (
    media_type in (
      'youtube',
      'spotify_episode',
      'spotify_show',
      'mp3',
      'video_file',
      'srt',
      'cover'
    )
  ),
  title text not null default '',
  url text,
  embed_url text,
  status text not null default 'pending'
    check (status in ('pending', 'available', 'hidden')),
  published_at timestamptz,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.site_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'active' check (status in ('active', 'cancelled')),
  subscribed_at timestamptz not null default now(),
  cancelled_at timestamptz,
  unique (user_id)
);

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists debates_publication_idx
  on public.debates (status, publish_at desc);

create index if not exists debate_segments_debate_order_idx
  on public.debate_segments (debate_id, sort_order);

create index if not exists debate_scorecards_debate_order_idx
  on public.debate_scorecards (debate_id, sort_order);

create index if not exists debate_media_debate_type_idx
  on public.debate_media (debate_id, media_type, status);

create index if not exists site_subscriptions_status_idx
  on public.site_subscriptions (status);

alter table public.debates enable row level security;
alter table public.debate_segments enable row level security;
alter table public.debate_scorecards enable row level security;
alter table public.debate_media enable row level security;
alter table public.site_subscriptions enable row level security;
alter table public.admin_audit_logs enable row level security;

drop policy if exists "Public can read published debates" on public.debates;
create policy "Public can read published debates"
  on public.debates
  for select
  using (
    status = 'published'
    and (publish_at is null or publish_at <= now())
  );

drop policy if exists "Admins can manage debates" on public.debates;
create policy "Admins can manage debates"
  on public.debates
  for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "Public can read published debate segments" on public.debate_segments;
create policy "Public can read published debate segments"
  on public.debate_segments
  for select
  using (
    exists (
      select 1
      from public.debates
      where debates.id = debate_segments.debate_id
        and debates.status = 'published'
        and (debates.publish_at is null or debates.publish_at <= now())
    )
  );

drop policy if exists "Admins can manage debate segments" on public.debate_segments;
create policy "Admins can manage debate segments"
  on public.debate_segments
  for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "Public can read published scorecards" on public.debate_scorecards;
create policy "Public can read published scorecards"
  on public.debate_scorecards
  for select
  using (
    exists (
      select 1
      from public.debates
      where debates.id = debate_scorecards.debate_id
        and debates.status = 'published'
        and (debates.publish_at is null or debates.publish_at <= now())
    )
  );

drop policy if exists "Admins can manage scorecards" on public.debate_scorecards;
create policy "Admins can manage scorecards"
  on public.debate_scorecards
  for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "Public can read published media" on public.debate_media;
create policy "Public can read published media"
  on public.debate_media
  for select
  using (
    status = 'available'
    and exists (
      select 1
      from public.debates
      where debates.id = debate_media.debate_id
        and debates.status = 'published'
        and (debates.publish_at is null or debates.publish_at <= now())
    )
  );

drop policy if exists "Admins can manage media" on public.debate_media;
create policy "Admins can manage media"
  on public.debate_media
  for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "Users can read own subscription" on public.site_subscriptions;
create policy "Users can read own subscription"
  on public.site_subscriptions
  for select
  to authenticated
  using (auth.uid() = user_id or public.is_admin());

drop policy if exists "Users can subscribe" on public.site_subscriptions;
create policy "Users can subscribe"
  on public.site_subscriptions
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own subscription" on public.site_subscriptions;
create policy "Users can update own subscription"
  on public.site_subscriptions
  for update
  to authenticated
  using (auth.uid() = user_id or public.is_admin())
  with check (auth.uid() = user_id or public.is_admin());

drop policy if exists "Admins can read audit logs" on public.admin_audit_logs;
create policy "Admins can read audit logs"
  on public.admin_audit_logs
  for select
  to authenticated
  using (public.is_admin());

drop policy if exists "Admins can add audit logs" on public.admin_audit_logs;
create policy "Admins can add audit logs"
  on public.admin_audit_logs
  for insert
  to authenticated
  with check (public.is_admin());

create or replace view public.public_site_subscription_count
with (security_invoker = true)
as
select count(*)::bigint as subscriber_count
from public.site_subscriptions
where status = 'active';

grant select on public.public_site_subscription_count to anon, authenticated;

