create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  avatar_url text,
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.debate_likes (
  debate_id text not null,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (debate_id, user_id)
);

create table if not exists public.debate_comments (
  id bigint generated by default as identity primary key,
  debate_id text not null,
  user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (
    char_length(trim(body)) between 1 and 1000
  ),
  created_at timestamptz not null default now()
);

create table if not exists public.debate_segment_likes (
  debate_id text not null,
  segment_id text not null,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (debate_id, segment_id, user_id)
);

create table if not exists public.debate_daily_views (
  debate_id text not null,
  view_date date not null default current_date,
  view_count integer not null default 0 check (view_count >= 0),
  updated_at timestamptz not null default now(),
  primary key (debate_id, view_date)
);

create index if not exists debate_likes_debate_id_idx
  on public.debate_likes (debate_id);

create index if not exists debate_comments_debate_id_created_at_idx
  on public.debate_comments (debate_id, created_at desc);

create index if not exists debate_segment_likes_debate_segment_idx
  on public.debate_segment_likes (debate_id, segment_id);

create index if not exists debate_daily_views_debate_date_idx
  on public.debate_daily_views (debate_id, view_date desc);

create or replace function public.increment_debate_daily_view(input_debate_id text)
returns table(today_count integer, total_count bigint)
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.debate_daily_views (debate_id, view_date, view_count)
  values (input_debate_id, current_date, 1)
  on conflict (debate_id, view_date)
  do update
  set
    view_count = public.debate_daily_views.view_count + 1,
    updated_at = now();

  return query
  select
    coalesce(sum(view_count) filter (where view_date = current_date), 0)::integer as today_count,
    coalesce(sum(view_count), 0)::bigint as total_count
  from public.debate_daily_views
  where debate_id = input_debate_id;
end;
$$;

grant execute on function public.increment_debate_daily_view(text) to anon, authenticated;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name, avatar_url)
  values (
    new.id,
    coalesce(
      new.raw_user_meta_data ->> 'full_name',
      new.raw_user_meta_data ->> 'name',
      split_part(new.email, '@', 1)
    ),
    new.raw_user_meta_data ->> 'avatar_url'
  )
  on conflict (id) do update
  set
    display_name = excluded.display_name,
    avatar_url = excluded.avatar_url;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.debate_likes enable row level security;
alter table public.debate_comments enable row level security;
alter table public.debate_segment_likes enable row level security;
alter table public.debate_daily_views enable row level security;

drop policy if exists "Profiles are visible to everyone" on public.profiles;
create policy "Profiles are visible to everyone"
  on public.profiles
  for select
  using (true);

drop policy if exists "Anyone can read likes" on public.debate_likes;
create policy "Anyone can read likes"
  on public.debate_likes
  for select
  using (true);

drop policy if exists "Users can like debates" on public.debate_likes;
create policy "Users can like debates"
  on public.debate_likes
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Users can remove their likes" on public.debate_likes;
create policy "Users can remove their likes"
  on public.debate_likes
  for delete
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Anyone can read comments" on public.debate_comments;
create policy "Anyone can read comments"
  on public.debate_comments
  for select
  using (true);

drop policy if exists "Users can add comments" on public.debate_comments;
create policy "Users can add comments"
  on public.debate_comments
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Admins can delete comments" on public.debate_comments;
create policy "Admins can delete comments"
  on public.debate_comments
  for delete
  to authenticated
  using (
    exists (
      select 1
      from public.profiles
      where profiles.id = auth.uid()
        and profiles.is_admin = true
    )
  );

drop policy if exists "Anyone can read segment likes" on public.debate_segment_likes;
create policy "Anyone can read segment likes"
  on public.debate_segment_likes
  for select
  using (true);

drop policy if exists "Users can like debate segments" on public.debate_segment_likes;
create policy "Users can like debate segments"
  on public.debate_segment_likes
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Users can remove their segment likes" on public.debate_segment_likes;
create policy "Users can remove their segment likes"
  on public.debate_segment_likes
  for delete
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Anyone can read debate views" on public.debate_daily_views;
create policy "Anyone can read debate views"
  on public.debate_daily_views
  for select
  using (true);
